spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: manu
    url: jdbc:h2:mem:testdb
    username: manu
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
app-msgs:
 messages:
   planSavedSucess: Saved Sucessfull
   planSaveUnsucess: Saved UnSucessfull
   planDeleteSucess: Deleted Sucessfull
   planDeleteUnsucess: Deleted Unsucessfull
   planStatusActivated: Plan Activated
   planStatusDeactivated: Plan Deactivated
    
